// some data was reshaped for key: value searching

export interface Player {
    code: number,
    assists: number,
    birth_date: string,
    bonus: number,
    bps: number,
    can_select: boolean,
    can_transact: boolean,
    chance_of_playing_next_round: number | null,
    chance_of_playing_this_round: number | null,
    clean_sheets: number,
    clean_sheets_per_90: number,
    clearances_blocks_interceptions: number,
    corners_and_indirect_freekicks_order: number | null,
    corners_and_indirect_freekicks_text: string,
    cost_change_event: number, 
    cost_change_event_fall: number,
    cost_change_start: number,
    cost_change_start_fall: number,
    creativity: string,
    creativity_rank: number,
    creativity_rank_type: number,
    defensive_contribution: number,
    defensive_contribution_per_90: number,
    direct_freekicks_order: number | null,
    direct_freekicks_text: string,
    dreamteam_count: number,
    element_type: number,
    ep_next: string,
    ep_this: string,
    event_points: number,
    expected_assists: string,
    expected_assists_per_90: number,
    expected_goal_involvements: string,
    expected_goal_involvements_per_90: number,
    expected_goals: string,
    expected_goals_conceded: string,
    expected_goals_conceded_per_90: number,
    expected_goals_per_90: number,
    first_name: string,
    form: string,
    form_rank: number,
    form_rank_type: number,
    goals_conceded: number,
    goals_conceded_per_90: number,
    goals_scored: number,
    has_temporary_code: boolean,
    ict_index: string,
    ict_index_rank: number,
    ict_index_rank_type: number,
    id: number,
    in_dreamteam: boolean,
    influence: string,
    influence_rank: number,
    influence_rank_type: number,
    minutes: number,
    news: string,
    news_added: string | null,
    now_cost: number,
    now_cost_rank: number,
    now_cost_rank_type: number,
    opta_code: string,
    own_goals: number,
    penalties_missed: number,
    penalties_order: number | null,
    penalties_saved: number,
    penalties_text: string,
    photo: string,
    points_per_game: string,
    points_per_game_rank: number,
    points_per_game_rank_type: number,
    recoveries: number,
    red_cards: number,
    region: number,
    removed: boolean,
    saves: number,
    saves_per_90: number,
    second_name: string,
    selected_by_percent: string,
    selected_rank: number,
    selected_rank_type: number,
    special: boolean,
    squad_number: number | null,
    starts: number,
    starts_per_90: number,
    status: string,
    tackles: number,
    team: number,
    team_code: number,
    team_join_date: string,
    threat: string,
    threat_rank: number,
    threat_rank_type: number,
    total_points: number,
    transfers_in: number,
    transfers_in_event: number,
    transfers_out: number,
    transfers_out_event: number,
    value_form: string,
    value_season: string,
    web_name: string
}

export interface Chip {
    chip_name: string,
    num_played: number
}

export interface Gameweek {
    id: number,
    average_entry_score: number,
    can_enter: boolean,
    can_manage: boolean,
    chip_plays: Chip[],
    cup_leagues_created: boolean,
    data_checked: boolean,
    deadline_time: string,
    deadline_time_epoch: number,
    deadline_time_game_offset: number,
    finished: boolean,
    h2h_ko_matches_created: boolean,
    highest_score: number,
    highest_scoring_entry: number,
    is_current: boolean,
    is_next: boolean,
    is_previous: boolean,
    most_captained: number,
    most_selected: number,
    most_transferred_in: number,
    most_vice_captained: number,
    name: string,
    ranked_count: number,
    release_time: null,
    released: boolean,
    top_element: number,
    top_element_info: {
        id: number,
        points: number,
    }
}

export interface Team {
    id: number,
    code: number,
    draw: number,
    form: string | null,
    loss: number,
    name: string,
    played: number,
    points: number,
    position: number,
    pulse_id: number,
    short_name: string,
    strength: number,
    strength_attack_away: number,
    strength_attack_home: number,
    strength_defence_away: number,
    strength_defence_home: number,
    strength_overall_away: number,
    strength_overall_home: number,
    team_division: number | null,
    unavailable: boolean,
    win: number
}

export interface Bootstrap {
    total_managers: number,
    players: {
        [key: number]: Player
    },
    gameweeks: Gameweek[],
    currentGW: Gameweek | null | undefined,
    teams: {
        [key: number]: Team
    }
}